// tests for rest/test
// Generated by serverless-mocha-plugin

var mod = require('../rest/subscription/handler.js');
var mochaPlugin = require('serverless-mocha-plugin');
var wrapper = mochaPlugin.lambdaWrapper;
var expect = mochaPlugin.chai.expect; 

wrapper.init(mod);

describe('rest/test', function() {
  it('implement tests here', function(done) {
    wrapper.run({}, function(err, response) { 
      console.log(response)   
      done('no tests implemented'); 
    });
  });
});
